# -*- coding: utf-8 -*-
"""lab 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wacC7b7zzQLHRAN30kLv3QeG9c-3_mM4

Question: 1
Maximize Z = 3x + 2y subject to x + y ≤ 4, x ≤ 2, y ≤ 3, x,y ≥ 0
"""

import pulp
lp = pulp.LpProblem("LPP1", pulp.LpMaximize)
x = pulp.LpVariable('x', lowBound=0)
y = pulp.LpVariable('y', lowBound=0)
lp += 3*x + 2*y
lp += x + y <= 4
lp += x <= 2
lp += y <= 3
lp.solve()
print(x.value(), y.value(), pulp.value(lp.objective))

"""Question: 2
Maximize Z = 5x + 4y subject to 6x + 4y ≤ 24, x + 2y ≤ 6
"""

import pulp
lp = pulp.LpProblem("LPP2", pulp.LpMaximize)
x = pulp.LpVariable('x', lowBound=0)
y = pulp.LpVariable('y', lowBound=0)
lp += 5*x + 4*y
lp += 6*x + 4*y <= 24
lp += x + 2*y <= 6
lp.solve()
print(x.value(), y.value(), pulp.value(lp.objective))

"""Question: 3
Minimize Z = x + y subject to 2x + y ≥ 6, x + 2y ≥ 6
"""

import pulp
lp = pulp.LpProblem("LPP3", pulp.LpMinimize)
x = pulp.LpVariable('x', lowBound=0)
y = pulp.LpVariable('y', lowBound=0)
lp += x + y
lp += 2*x + y >= 6

lp += x + 2*y >= 6
lp.solve()
print(x.value(), y.value(), pulp.value(lp.objective))

"""Question: 4
Maximize Z = 4x + 3y subject to 2x + y ≤ 8, x + 2y ≤ 8
"""

import pulp
lp = pulp.LpProblem("LPP4", pulp.LpMaximize)
x = pulp.LpVariable('x', lowBound=0)
y = pulp.LpVariable('y', lowBound=0)
lp += 4*x + 3*y
lp += 2*x + y <= 8
lp += x + 2*y <= 8
lp.solve()
print(x.value(), y.value(), pulp.value(lp.objective))

"""Question: 5
Minimize Z = 3x + 5y subject to x + y ≥ 4, x ≤ 3, y ≤ 3
"""

import pulp
lp = pulp.LpProblem("LPP5", pulp.LpMinimize)
x = pulp.LpVariable('x', lowBound=0)
y = pulp.LpVariable('y', lowBound=0)
lp += 3*x + 5*y
lp += x + y >= 4
lp += x <= 3
lp += y <= 3
lp.solve()
print(x.value(), y.value(), pulp.value(lp.objective))

Question: 6
Maximize Z = 6x + 5y subject to x + y ≤ 5, 3x + 2y ≤ 12

import pulp
lp = pulp.LpProblem("LPP6", pulp.LpMaximize)
x = pulp.LpVariable('x', lowBound=0)

y = pulp.LpVariable('y', lowBound=0)
lp += 6*x + 5*y
lp += x + y <= 5
lp += 3*x + 2*y <= 12
lp.solve()
print(x.value(), y.value(), pulp.value(lp.objective))

"""Question:7
Minimize Z = 2x + 3y subject to x + y ≥ 5, x,y ≥ 1
"""

import pulp
lp = pulp.LpProblem("LPP7", pulp.LpMinimize)
x = pulp.LpVariable('x', lowBound=1)
y = pulp.LpVariable('y', lowBound=1)
lp += 2*x + 3*y
lp += x + y >= 5
lp.solve()
print(x.value(), y.value(), pulp.value(lp.objective))

"""Question: 8
Maximize Z = 7x + 6y subject to 2x + y ≤ 6, x + 2y ≤ 6
"""

import pulp
lp = pulp.LpProblem("LPP8", pulp.LpMaximize)
x = pulp.LpVariable('x', lowBound=0)
y = pulp.LpVariable('y', lowBound=0)
lp += 7*x + 6*y
lp += 2*x + y <= 6
lp += x + 2*y <= 6
lp.solve()
print(x.value(), y.value(), pulp.value(lp.objective))

"""Question: 9
Minimize Z = x + 4y subject to x + 2y ≥ 8, x ≥ 2
"""

import pulp
lp = pulp.LpProblem("LPP9", pulp.LpMinimize)
x = pulp.LpVariable('x', lowBound=2)
y = pulp.LpVariable('y', lowBound=0)

lp += x + 4*y
lp += x + 2*y >= 8
lp.solve()
print(x.value(), y.value(), pulp.value(lp.objective))

"""Question: 10
Maximize Z = 5x + 3y subject to x + y ≤ 7, x ≤ 4, y ≤ 5
"""

import pulp
lp = pulp.LpProblem("LPP10", pulp.LpMaximize)
x = pulp.LpVariable('x', lowBound=0)
y = pulp.LpVariable('y', lowBound=0)
lp += 5*x + 3*y
lp += x + y <= 7
lp += x <= 4
lp += y <= 5
lp.solve()
print(x.value(), y.value(), pulp.value(lp.objective))